### ISSUE TITLE
Door and motion sensor don't change state

### ISSUE THREAD

**Issue by marccie** [athombv/com.tuya#278] opened 2024-10-16 09:57 UTC
### Homey version

Homey Pro (Early 2023), v12.1.1

### Tuya app version

v1.4.1

### App diagnostics report ID

d68bea2c-327d-4056-8b87-cfe5a2029747

### Description

Door sensors and motion sensor don't receive information/webhooks of state of device. For example one motion sensors stays with state motion detected and won't change to no motion detected. Same for other motion sensors they don't detect motion, and the door sensors won't detect if the door is opened or closed. When I go to the smart life app of Tuya I can see that the sensor are working correct.

Device settings below are for the motion sensor that stays in on motion detected.

### Device specification

{
    "device": {
        "active_time": 1729071598,
        "biz_type": 0,
        "category": "pir",
        "create_time": 1729071598,
        "icon": "smart/icon/ay1513237774906SMBA3/a7a41ac3d2c8f786bbabff6e2674e6f6.png",
        "id": "bf1056d850c8443ad0rnr6",
        "ip": "<redacted>",
        "lat": "<redacted>",
        "local_key": "<redacted>",
        "lon": "<redacted>",
        "model": "ZBSM20WT",
        "name": "Bewegingssensor Do",
        "node_id": "a4c138eb439d5142",
        "online": true,
        "owner_id": "<redacted>",
        "product_id": "s6hzw8g2",
        "product_name": "Motion sensor",
        "status": [
            {
                "code": "pir",
                "value": "pir"
            },
            {
                "code": "battery_percentage",
                "value": 100
            }
        ],
        "sub": true,
        "time_zone": "+02:00",
        "uid": "<redacted>",
        "update_time": 1729071612,
        "uuid": "<redacted>"
    },
    "specifications": {
        "category": "pir",
        "functions": [],
        "status": [
            {
                "code": "pir",
                "type": "Enum",
                "values": "{\"range\":[\"pir\",\"none\"]}"
            },
            {
                "code": "battery_percentage",
                "type": "Integer",
                "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
            }
        ]
    },
    "data_points": [
        {
            "code": "pir_state",
            "custom_name": "",
            "dp_id": 1,
            "time": 1729071605961,
            "type": "enum",
            "value": "pir"
        },
        {
            "code": "battery_percentage",
            "custom_name": "",
            "dp_id": 4,
            "time": 1729071606575,
            "type": "value",
            "value": 100
        },
        {
            "code": "illuminance_value",
            "custom_name": "",
            "dp_id": 101,
            "time": 1729071628294,
            "type": "value",
            "value": 52
        },
        {
            "code": "charge_state",
            "custom_name": "",
            "dp_id": 102,
            "time": 1729071598734,
            "type": "bool",
            "value": false
        }
    ]
}

**Comment by bobvandevijver** [comment] 2024-10-16 10:03
Duplicate of #276. The relevant cloud component has been restored and updates should be coming in again. It might some time before we have catched up on all events, so please be patient 👍🏻

**Closed by bobvandevijver** 2024-10-16 10:03 UTC
Labels: bug
