### ISSUE TITLE
energy consumption is no longer recorded with tuya smart plug

### ISSUE THREAD

**Issue by wannes62** [athombv/com.tuya#277] opened 2024-10-15 21:26 UTC
### Homey version

2023 homey pro

### Tuya app version

1.4.1

### Description

since this morning the energy consumption is no longer registered with tuya smart plug.
The smart plug indicated 0 watts, so I restarted the tuya app.
Now the smart plug indicates 123 watts but remains on this, while the device connected to the smart plug does turn off. (freezer)
I restarted the tuya app again and then the smart plug indicates 55 watts, but does not change.
![IMG_0902](https://github.com/user-attachments/assets/1576cc3f-3eee-4fc6-9616-3da605022692)

**Comment by bobvandevijver** [comment] 2024-10-16 07:11
Duplicate of #276. There seems to be an issue with the message service at this time, we are looking into it.

**Closed by bobvandevijver** 2024-10-16 07:11 UTC
Labels: bug

**Comment by wannes62** [comment] 2024-10-16 19:41
It looks like that het problem is solved since 12am
![20241016_194016537_iOS](https://github.com/user-attachments/assets/7ffc7801-b364-477d-9add-a3832888ad18)
