### ISSUE TITLE
Add device group support

### ISSUE THREAD

**Issue by Mor46** [athombv/com.tuya#94] opened 2024-07-29 14:19 UTC
### Homey version

Homey Pro 2023

### Tuya app version

Tuya v1.1.0

### App diagnostics report ID

39c4511f-ceab-4db5-9768-b6c75dc4756a

### Description

I have my lamps (spotlights) via a gateway, see photos which gateway is linked to the smart tuya app. I created 10 groups for my lights in smart tuya app. under each group there are a few lamps. 

I have connected the smart tuya app to homey. I wanted to get all groups within Homey but it doesn't work. I can only get one group into homey and other groups can't get into homey.  
i have 30 spots and they are divided in 10 groups. so i can only see one group in homey. 
can you try to solve this problem? 

I would love to hear from you.  
![20240720_132856](https://github.com/user-attachments/assets/6ac61757-0a1e-46fc-8d16-5b18068133ca)
![20240720_132950](https://github.com/user-attachments/assets/e8006c7e-9e16-4ec8-a08d-5e304158b02b)

thank you.  
kind regards from, Mor 

### Device specification

  { 
"device"...

**Comment by bobvandevijver** [comment] 2024-07-29 14:29
I believe you are looking for a way to control Tuya groups: that is currently not supported. From you log it looks like you did manage to connect a socket correctly.

It seems that when a device is combined into a group, it is no longer returned in the device list, which would explain why it seems you cannot add them as other. Can you validate that the one device you are able to add is your Tuya socket? It would help if you post the complete content of the device specification, instead of only the start.

You can also try to remove one of your lights from the Tuya group, so you can add it as a single light to Homey.

We will need to validate this internally as well when you have confirmed this hypothesis is correct.

**Comment by Mor46** [comment] 2024-07-31 16:00
hello, thank you for your email. Luckily I was able to connect all the socket  to homy. those are sockets that were in smartlife. I have linked a group of my spotlights for you so you can see the report. 4da94f0f-4679-4f1c-9e95-a8c64c18bb57it is not convenient to connect a spotlight to homey because I have 30 spotlights and it is too difficult to connect so many spotlights one by one turn on and change color. it is not possible to copy entire specifications. i now have specifications of a group of lights. this is the only one i see and you can not click and copy. see photo in attachment. Kind regards Sent from my Galaxy  
-------- Oorspronkelijk bericht --------Van: Bob van de Vijver ***@***.***> Datum: 29-07-2024  16:30  (GMT+01:00) Aan: "athombv/com.tuya" ***@***.***> Cc: Mor46 ***@***.***>, Author ***@***.***> Onderwerp: Re: [athombv/com.tuya] import lamps from toya into homey  (Issue #94) 
I believe you are looking for a way to control Tuya groups: that is currently not supported. From you log it looks like you did manage to connect a socket correctly.
It seems that when a device is combined into a group, it is no longer returned in the device list, which would explain why it seems you cannot add them as other. Can you validate that the one device you are able to add is your Tuya socket? It would help if you post the complete content of the device specification, instead of only the start.
You can also try to remove one of your lights from the Tuya group, so you can add it as a single light to Homey.
We will need to validate this internally as well when you have confirmed this hypothesis is correct.

**Comment by Mor46** [comment] 2024-07-31 17:22
Hallo, Kan ik mijn mails ook in het Nederlands schrijven? Met vriendelijke groet/ Kind regards Morteza Abdi Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bob van de Vijver ***@***.***> Datum: 29-07-2024  16:30  (GMT+01:00) Aan: "athombv/com.tuya" ***@***.***> Cc: Mor46 ***@***.***>, Author ***@***.***> Onderwerp: Re: [athombv/com.tuya] import lamps from toya into homey  (Issue #94) 
I believe you are looking for a way to control Tuya groups: that is currently not supported. From you log it looks like you did manage to connect a socket correctly.
It seems that when a device is combined into a group, it is no longer returned in the device list, which would explain why it seems you cannot add them as other. Can you validate that the one device you are able to add is your Tuya socket? It would help if you post the complete content of the device specification, instead of only the start.
You can also try to remove one of your lights from the Tuya group, so you can add it as a single light to Homey.
We will need to validate this internally as well when you have confirmed this hypothesis is correct.

**Comment by bobvandevijver** [comment] 2024-07-31 19:26
We prefer to keep it in English here so most people should be able to follow the request.

Attachments to emails are not transferred to the Github issue, so I cannot see it. However, without the device specification we cannot do anything. One way to copy it is using https://my.homey.app using a laptop/desktop and keep clicking the specification until it is selected.

**Comment by Mor46** [comment] 2024-07-31 20:40
Hallo ,

 

okay. my english is not that good but i am going to try because i want you to find a solution .

it worked. This is the specification.

 

Do you need more?

 

 

 

{ "device": { "active_time": 1706981852, "biz_type": 0, "category": "dj", "create_time": 1706193729, "icon": "smart/icon/ay1544595242978Akat0/40bef61b8cafd1ee0e8e8fdc5b41d444.png", "id": "bf69b888fffdb0e614onkk", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "WL-Box2", "name": "AAN UIT", "online": true, "owner_id": "<redacted>", "product_id": "2vc0xj19d766eq0k", "product_name": "2.4G Gateway", "status": [ { "code": "switch_led", "value": false }, { "code": "work_mode", "value": "colour" }, { "code": "bright_value_v2", "value": 1000 }, { "code": "temp_value_v2", "value": 0 }, { "code": "colour_data_v2", "value": "{\"h\":192,\"s\":1000,\"v\":190}" }, { "code": "countdown_1", "value": 0 }, { "code": "control_data", "value": "" } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1722437541, "uuid": "<redacted>" }, "specifications": { "category": "dj", "functions": [ { "code": "switch_led", "desc": "{}", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "desc": "{\"range\":[\"white\",\"colour\"]}", "name": "工作模式", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\"]}" }, { "code": "bright_value_v2", "desc": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}", "name": "亮度", "type": "Integer", "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "temp_value_v2", "desc": "{\"unit\":\"\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}", "name": "色温", "type": "Integer", "values": "{\"unit\":\"\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data_v2", "desc": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}", "name": "彩光模式值", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown_1", "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "name": "倒计时", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "control_data", "desc": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "调节模式值", "type": "Json", "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" } ], "status": [ { "code": "switch_led", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "name": "模式", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\"]}" }, { "code": "bright_value_v2", "name": "亮度", "type": "Integer", "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "temp_value_v2", "name": "冷暖", "type": "Integer", "values": "{\"unit\":\"\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data_v2", "name": "彩光模式", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown_1", "name": "倒计时", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "control_data", "name": "调节控制", "type": "Json", "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" } ] } }

 

Met vriendelijke groet, 

Morteza Abdi 

 

Van: Bob van de Vijver ***@***.***> 
Verzonden: woensdag 31 juli 2024 21:27
Aan: athombv/com.tuya ***@***.***>
CC: Mor46 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [athombv/com.tuya] import lamps from toya into homey (Issue #94)

 

We prefer to keep it in English here so most people should be able to follow the request.

Attachments to emails are not transferred to the Github issue, so I cannot see it. However, without the device specification we cannot do anything. One way to copy it is using https://my.homey.app using a laptop/desktop and keep clicking the specification until it is selected.

**Comment by bobvandevijver** [comment] 2024-08-01 08:01
Your English is just fine :+1:

The specification you posted is for the gateway, and as you are not seeing the lamp it confirms my suspicion. We have enough information for now, we will be looking into this.

**Comment by bobvandevijver** [comment] 2024-08-02 14:47
@Mor46 According to our tests lights that have been placed in a device group can also be added individually. We have decided against implementing group support for now as they are not very well defined which does not really match the category structure we use now. 

In any case, within Homey you should be able to use Moods to group lights and control them simultaneously. You should be able to add all your lights individually.

**Closed by bobvandevijver** 2024-08-02 14:47 UTC
Labels: enhancement, confirmed

**Comment by Mor46** [comment] 2024-08-02 18:06
ok i will try. thanks for looking for solution. there is one more problem. If you log in to Tuya via Homy to get your products within Homy and then you want to log in to Smartlife, it does not work. you can no longer select smartlife to log in to bring products into homy.  you automatically go to tuya every time and you stay logged in there. am i doing something wrong? Kind regards Morteza Abdi Sent from my Galaxy  
-------- Oorspronkelijk bericht --------Van: Bob van de Vijver ***@***.***> Datum: 02-08-2024  16:47  (GMT+01:00) Aan: "athombv/com.tuya" ***@***.***> Cc: Mor46 ***@***.***>, Mention ***@***.***> Onderwerp: Re: [athombv/com.tuya] Add device group support (Issue #94) 
@Mor46 According to our tests lights that have been placed in a device group can also be added individually. We have decided against implementing group support for now as they are not very well defined which does not really match the category structure we use now.
In any case, within Homey you should be able to use Moods to group lights and control them simultaneously. You should be able to add all your lights individually.

**Comment by bobvandevijver** [comment] 2024-08-05 07:48
As mentioned on https://support.homey.app/hc/en-us/articles/14504423087644-Connecting-Tuya-with-Homey you will need to make sure that all your Tuya devices are in the same app. At this time it is not possible to use both.

**Comment by Mor46** [comment] 2024-08-05 12:32
I tried adding my lights one by one first to tuya . Tuya sees each light as a zone.  and not as an individual lamp and this can be done under the SET tab. see photo below. 

![Screenshot_20240805_140940_Tuya Smart](https://github.com/user-attachments/assets/6b18f042-66ee-4f95-aa04-d4c9c34c93fe) 

when you want to add all lamps one by one in homey then homy sees a zone and that is a lamp. further you can not add other lamps/zone to homey. see photo below that only zone is visible and not a lamp. 

![Screenshot_20240805_140337_Tuya Smart](https://github.com/user-attachments/assets/d99afcb9-042f-424d-9484-30e98f5e2d46)

    what now? is there a solution?

**Comment by bobvandevijver** [comment] 2024-08-06 07:26
I'm afraid there isn't much we can't do if Tuya only exposes the box as device.
