### ISSUE TITLE
send raw data

### ISSUE THREAD

**Issue by robertomario76** [athombv/com.tuya#64] opened 2024-07-22 15:00 UTC
in the tuya cloud app there is the possibility of receiving all the raw data from the tuya server, these are very useful for all those objects that have not yet been implemented, with a little IT knowledge and experience it is possible to write scripts and generate virtual devices

**Comment by bobvandevijver** [comment] 2024-07-22 15:13
This is a duplicate of #20, we are working on this!

**Closed by bobvandevijver** 2024-07-22 15:13 UTC
