### ISSUE TITLE
Lsc Moodlight can’t change color or dimmer

### ISSUE THREAD

**Issue by Zen-Dar** [athombv/com.tuya#162] opened 2024-08-18 10:07 UTC
### Homey version

2023 Homey Pro 12.0.0

### Tuya app version

V1.2.3

### App diagnostics report ID

abcb70de-d249-443f-a392-aa160ae26d82

### Description

LSC mood light (action) can’t dimmer or change color. Request fail with Unknown Error (code 501). Just turn on and off 

### Device specification

{ "device" {

**Comment by bobvandevijver** [comment] 2024-08-19 07:37
Thank you for your report, but I believe this to be a temporary issue with the Tuya cloud or your device, and not an issue with this app.

**Comment by bobvandevijver** [comment] 2024-08-19 13:22
Can you post the device specification?

**Comment by Zen-Dar** [comment] 2024-08-19 15:16
As i wrote when submitting the bug, in Advanced i can see no info (screenshot)
![IMG_6818](https://github.com/user-attachments/assets/4bf4369d-2991-4f02-b32c-a0603b1b979e)

**Comment by bobvandevijver** [comment] 2024-08-19 15:21
You can use https://my.homey.app (as noted in the instructions shown when you opened this issue) to retrieve the full value.

**Comment by Zen-Dar** [comment] 2024-08-19 16:05
{ "device": { "active_time": 1718380782, "biz_type": 0, "category": "fwd", "create_time": 1718380782, "icon": "smart/icon/ay1541056239985fDGjj/e643a2ce7eedf2cf13e90232633991d4.png", "id": "bfed98b08f62429dc343go", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "5325000800", "name": "LSC Moodlight", "online": true, "owner_id": "<redacted>", "product_id": "rwdljihfkp4ubn6f", "product_name": "LSC Moodlight", "status": [ { "code": "switch_led", "value": false }, { "code": "work_mode", "value": "colour" }, { "code": "bright_value", "value": 230 }, { "code": "colour_data", "value": "{\"h\":240,\"s\":297,\"v\":1000}" }, { "code": "scene_data", "value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":200,\"h\":0,\"s\":0,\"temperature\":1000,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}" }, { "code": "countdown", "value": 0 }, { "code": "rhythm_mode", "value": "AAAAAAA=" }, { "code": "sleep_mode", "value": "AAA=" }, { "code": "wakeup_mode", "value": "AAA=" } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1723877616, "uuid": "<redacted>" }, "specifications": { "category": "fwd", "functions": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "scene_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "music_data", "type": "Json", "values": "{}" }, { "code": "control_data", "type": "Json", "values": "{}" }, { "code": "rhythm_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "sleep_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "wakeup_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" } ], "status": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "scene_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "rhythm_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "sleep_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "wakeup_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" } ] }, "data_points": [ { "code": "switch_led", "custom_name": "", "dp_id": 20, "time": 1723974856172, "type": "bool", "value": false }, { "code": "work_mode", "custom_name": "", "dp_id": 21, "time": 1719822388982, "type": "enum", "value": "colour" }, { "code": "bright_value", "custom_name": "", "dp_id": 22, "time": 1719822388982, "type": "value", "value": 230 }, { "code": "colour_data", "custom_name": "", "dp_id": 24, "time": 1719822388982, "type": "string", "value": "00f0012903e8" }, { "code": "scene_data", "custom_name": "", "dp_id": 25, "time": 1719822388982, "type": "string", "value": "000e0d0000000000000000c803e8" }, { "code": "countdown", "custom_name": "", "dp_id": 26, "time": 1719822388982, "type": "value", "value": 0 }, { "code": "music_data", "custom_name": "", "dp_id": 27, "time": 1718380782103, "type": "string", "value": "" }, { "code": "control_data", "custom_name": "", "dp_id": 28, "time": 1718380782103, "type": "string", "value": "" }, { "code": "rhythm_mode", "custom_name": "", "dp_id": 30, "time": 1723877617450, "type": "raw", "value": "AAAAAAA=" }, { "code": "sleep_mode", "custom_name": "", "dp_id": 31, "time": 1723877617561, "type": "raw", "value": "AAA=" }, { "code": "wakeup_mode", "custom_name": "", "dp_id": 32, "time": 1723877617663, "type": "raw", "value": "AAA=" }, { "code": "power_memory", "custom_name": "", "dp_id": 33, "time": 1723877617765, "type": "raw", "value": "AAEA8AEpA+gA5gPo" }, { "code": "mic_music_data", "custom_name": "", "dp_id": 42, "time": 1719822388982, "type": "string", "value": "010000016432000003e8007803e800f003e8003c03e800b403e8012c03e8" }, { "code": "breathing_scene", "custom_name": "", "dp_id": 55, "time": 1718380782103, "type": "raw" } ] }

**Comment by bobvandevijver** [comment] 2024-08-20 10:33
I'm not 100% sure why this is happening, so we might need you to wait for the next release which adds some additional logging so you can generate a new app diagnostics report.

@JELoohuis Could this be caused by the `colour_data` specification being `{}`?

**Comment by Zen-Dar** [comment] 2024-08-20 10:48
Thanks a lot for your support. I have another Tuya light with different brand with same problem. Will post another thread with info (thannks to explain The retrieving method) Just in case it will give more infos

**Comment by bobvandevijver** [comment] 2024-08-22 15:31
We believe this should be fixed with the upcoming release.

**Closed by bobvandevijver** 2024-08-22 15:31 UTC
Labels: bug
