### ISSUE TITLE
Request Device: Action Battletron light

### ISSUE THREAD

**Issue by Plantje1978** [athombv/com.tuya#15] opened 2024-06-11 20:27 UTC
To request a new device, please run the Tuya app locally using Homey CLI.

```
2024-06-11T20:16:42.953Z [log] [ManagerDrivers] [Driver:light] Device: {"active_time":1705151676,"biz_type":0,"category":"dd","create_time":1705151676,"icon":"smart/icon/ay1578118863094h8YCV/dd0c14119f57a766178f0591e0929dc7.png","id":"bfd29132078f624af4f2oa","ip":"84.25.65.21","lat":"52.3835","local_key":"g0~Pk71&x~3@]?UD","lon":"6.1455","model":"6232000200","name":"Battletron Ball Bureau Jorg","online":true,"owner_id":"39161877","product_id":"yrg6a649fkozp1hw","product_name":"Battletron Ball Light","status":[{"code":"switch_led","value":false},{"code":"work_mode","value":"colour"},{"code":"colour_data","value":"{\"h\":220,\"s\":255,\"v\":1000}"},{"code":"countdown","value":0}],"sub":false,"time_zone":"+01:00","uid":"eu1633884783385gZ4NF","update_time":1716924690,"uuid":"3a805ba75623179a"}
```

The light is being added. The [Action Battletron light](https://www.action.com/nl-nl/p/3202652/battletron-gaming-lichtbol-razer-chroma/) cannot be dimmed. And as soon as it is controlled (changed color) and I check it in the Tuya Smart app it is dimmed to 0%.

**Comment by bobvandevijver** [comment] 2024-07-23 13:53
I am going to close this one to clean up tickets (duplicate of #13), but please open a new one with the requested information.

**Closed by bobvandevijver** 2024-07-23 13:53 UTC
Labels: device request
