### ISSUE TITLE
Device is unavailable and available at the same time

### ISSUE THREAD

**Issue by AndyGHenderson** [athombv/com.tuya#265] opened 2024-10-04 10:44 UTC
### Homey version

2023 Homey Pro 12.1.0

### Tuya app version

v1.4.0

### App diagnostics report ID

75dc3e4c-2a21-42e0-b20e-17a239bad85b

### Description

One of my bulbs (Bulb 10 in the diagnostics report) was showing the red triangle in the web version of the Homey app. I was able to turn it on and off via Smartlife app and Alexa (using Tuya skill). The really odd bit is that the icon in the Homey app turned on and off with the light while steadfastly insisting the device was unavailable - but at least part of the app thought it was available.

Restarting the Homey web page had no effect. Restarting Homey's Tuya app cleared the issue removing the red triangle.

When I tried to retrieve the device specification to complete this issue I got 'not available'. I deleted it and re-added it to get the specification below. The icon nows shows the bulb temperature which it didn't before (although it did appear in the Homey Android app).

Hard to know what extra diagnostics I can provide, but hoping the above might lead to a way to make the app more reliable.

### Device specification

```json
{
  "device": {
    "active_time": 1606220938,
    "biz_type": 18,
    "category": "dj",
    "create_time": 1606220938,
    "icon": "smart/icon/001460162698766TR4v1/310bac187f3622ff894b7adcbd9846eb.png",
    "id": "bf8db5e8913bd8a6b6vvvk",
    "ip": "<redacted>",
    "lat": "<redacted>",
    "local_key": "<redacted>",
    "lon": "<redacted>",
    "model": "",
    "name": "Bulb 10",
    "online": true,
    "owner_id": "<redacted>",
    "product_id": "mytbo5nh9rcsn6wv",
    "product_name": "Smart Led CW",
    "status": [
      {
        "code": "switch_led",
        "value": false
      },
      {
        "code": "work_mode",
        "value": "white"
      },
      {
        "code": "bright_value_v2",
        "value": 10
      },
      {
        "code": "temp_value_v2",
        "value": 0
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "control_data",
        "value": ""
      }
    ],
    "sub": false,
    "time_zone": "+00:00",
    "uid": "<redacted>",
    "update_time": 1727974029,
    "uuid": "<redacted>"
  },
  "specifications": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ]
  },
  "data_points": [
    {
      "code": "switch_led",
      "custom_name": "",
      "dp_id": 20,
      "time": 1728036728898,
      "type": "bool",
      "value": false
    },
    {
      "code": "work_mode",
      "custom_name": "",
      "dp_id": 21,
      "time": 1727995143954,
      "type": "enum",
      "value": "white"
    },
    {
      "code": "bright_value",
      "custom_name": "",
      "dp_id": 22,
      "time": 1727995147795,
      "type": "value",
      "value": 10
    },
    {
      "code": "temp_value",
      "custom_name": "",
      "dp_id": 23,
      "time": 1727995147800,
      "type": "value",
      "value": 0
    },
    {
      "code": "countdown",
      "custom_name": "",
      "dp_id": 26,
      "time": 1725916517377,
      "type": "value",
      "value": 0
    },
    {
      "code": "control_data",
      "custom_name": "",
      "dp_id": 28,
      "time": 1606220938715,
      "type": "string",
      "value": ""
    }
  ]
}
```

**Comment by bobvandevijver** [comment] 2024-10-07 09:44
Thanks for the report!

If `not available` was shown you almost certainly added this light with an old version of the Tuya app. While we try to migrate all devices (if required) when the app is updates, it sometimes can fail. I believe that that has happened here, which can be caused by the light being offline during migration. Another possibility is that the online notification for some reason did not reach your Homey while other updates were coming in.

As I'm not seeing any error in the log you've created and your issue seems to be fixed by re-adding the device, I am going to close this ticket. If you experience any other issues you can always open another ticket.

**Closed by bobvandevijver** 2024-10-07 09:44 UTC
Labels: bug
